### ISSUE TITLE
[Add Host]

### ISSUE THREAD

**Issue by hartmanziga** [sbpp/hosts#5]
**Name**: MargeHost ( https://margehost.com/ )
**Minimal plan**: 1.80€/month
**Type**: Shared
**Data center locations**: Germany
**Trial**: No
**Free**: No
**Ideal for**: Webserver MySQL database

**Comment by Groruk** [comment]
The landing page seems to be quite a work in progress, half of the links don't have a proper `href` set.
Also I can't find any legal information (privacy policy, gdpr, terms of service, owner / company behind the service) on the website, which seems kind of sketchy.

For the time being I would close the issue and wait until their website is finished and some legal information has been added.
